
[package]
name = "mad_qats"
version = "0.1.0"
edition = "2021"
authors = ["Benjamin Flanagin <flanagin@system76.com>"]

[dependencies]
qmetaobject = "0.2"
qttypes = "0.2"
cstr = "0.2"


[build-dependencies]
cpp_build = "0.5.6"
